name: Mirror to Repo A

on:
  push:
    branches:
      - main  # Trigger on commits to 'main'

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo B (this repo)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Important: fetch full history for mirroring

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add and push to Repo A (Azure target repo)
        env:
          AZURE_PAT: ${{ secrets.AZURE_PAT }}
        run: |
          git remote add repo-a https://ECCC-DevOps:${AZURE_PAT}@dev.azure.com/ECCC-DevOps/SPB-EAD-AMD/_git/sync-3
          git remote -v
          git fetch repo-a
          git push repo-a HEAD:refs/heads/ssi-mirror
